fcrepo:
    base: http://localhost:8080/rest/test/
source_relations: source-data/sample-data/relations.rdf
source_data: source-data/sample-data/50000.rdf
multiplier: 50
threads: 8
load_binary_data: 0
